version: '3.8'

services:
  # Python FastAPI Backend
  api:
    build:
      context: ./python-backend
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT=development
    ports:
      - "8000:8000"
    volumes:
      - ./python-backend:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # React Frontend
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=http://localhost:8000
    ports:
      - "3000:80"
    depends_on:
      api:
        condition: service_healthy

volumes:
  webapp_node_modules:
