name: mortgage-calculator-app
region: lon
domains:
- domain: mortgagepayoffcalculator.io
  type: PRIMARY
- domain: www.mortgagepayoffcalculator.io
  type: ALIAS

services:
# React Frontend (Static Site)
- name: frontend
  source_dir: /
  github:
    repo: C0n0r92/mortgage_payoff_calculator
    branch: main
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  build_command: npm install && npm run build
  run_command: npx serve -s dist -l $PORT
  envs:
  - key: NODE_ENV
    value: production
  - key: VITE_GA_MEASUREMENT_ID
    value: "G-43FMLL1ZG0"
  routes:
  - path: /

static_sites: []
