name: mortgage-calculator-app
services:
# Rails Backend API - Simple configuration
- name: rails-api
  source_dir: /
  github:
    repo: C0n0r92/mortgage_payoff_calculator
    branch: main
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  environment_slug: ruby
  envs:
  - key: RAILS_ENV
    value: production
  - key: RAILS_MASTER_KEY
    value: ae744e6df9969de7459815939e7f7ed3
  - key: DATABASE_URL
    value: ${managed-db.DATABASE_URL}
  routes:
  - path: /api
    preserve_path_prefix: true

databases:
- name: managed-db
  engine: PG
  production: true