name: mortgage-calculator-app
services:
# Python Backend API
- name: api
  source_dir: /
  github:
    repo: C0n0r92/calc2
    branch: main
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8000
  build_command: pip install -r requirements.txt
  run_command: python -m uvicorn main:app --host 0.0.0.0 --port 8000 --log-level info
  environment_slug: python
  envs:
  - key: ENVIRONMENT
    scope: RUN_AND_BUILD_TIME
    value: production
  - key: ALLOWED_ORIGINS
    scope: RUN_AND_BUILD_TIME
    value: "*"
  routes:
  - path: /api
    preserve_path_prefix: true
  health_check:
    http_path: /

# React Frontend
- name: frontend
  source_dir: /frontend
  github:
    repo: C0n0r92/calc2
    branch: main
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  build_command: npm install --include=dev && npm run build
  run_command: npm run preview -- --host 0.0.0.0 --port 3000
  environment_slug: node-js
  envs:
  - key: NODE_ENV
    value: production
  - key: VITE_API_URL
    value: "/api"
  - key: VITE_GA_MEASUREMENT_ID
    value: "G-43FMLL1ZG0"
  routes:
  - path: /
  health_check:
    http_path: /
    port: 3000
    initial_delay_seconds: 30
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3

alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
