name: mortgage-calculator-app
region: lon
domains:
- domain: mortgagepayoffcalculator.io
  type: PRIMARY
- domain: www.mortgagepayoffcalculator.io
  type: ALIAS

services:
# Rails Backend API
- name: rails-api
  environment_slug: ruby
  source_dir: /mortgage_calculator_api
  github:
    repo: C0n0r92/mortgage_payoff_calculator
    branch: main
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  build_command: bundle install --deployment --without development test && bundle exec rails assets:precompile && bundle exec rails db:prepare
  run_command: bundle exec rails server -b 0.0.0.0 -p 8080
  envs:
  - key: RAILS_ENV
    value: production
  - key: RAILS_SERVE_STATIC_FILES
    value: "true"
  - key: RAILS_LOG_TO_STDOUT
    value: "true"
  - key: RAILS_FORCE_SSL
    value: "false"
  - key: PORT
    value: "8080"
  - key: DATABASE_URL
    value: "${managed-db.DATABASE_URL}"
    scope: RUN_TIME
  - key: SECRET_KEY_BASE
    value: "7cf6edda93cf09a4f69db15991af58789ee1264cd2ae54d49a9f52cedea88e291aa352a0d9d67e5feb1a63eb093ef9ff2c7f7e540867d1ab992e7a1d942e92d9"
  routes:
  - path: /api
    preserve_path_prefix: true

# React Frontend
- name: frontend
  environment_slug: node-js
  source_dir: /
  github:
    repo: C0n0r92/mortgage_payoff_calculator
    branch: main
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  build_command: npm install && npm run build
  run_command: npx serve -s dist -l 3000
  envs:
  - key: NODE_ENV
    value: production
  - key: VITE_API_URL
    value: "/api"
  - key: VITE_GA_MEASUREMENT_ID
    value: "G-43FMLL1ZG0"
  routes:
  - path: /

databases:
- name: managed-db
  cluster_name: mortgage-calculator-cluster
  engine: PG
  production: true

static_sites: []
