name: mortgage-calculator-app
region: nyc
services:
- name: python-api
  source_dir: python-backend
  github:
    repo: C0n0r92/calc2
    branch: main
    deploy_on_push: true
  dockerfile_path: Dockerfile
  http_port: 8000
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-1gb
  health_check:
    http_path: /health
  envs:
  - key: ENVIRONMENT
    value: production
  - key: ALLOWED_ORIGINS
    value: "https://mortgage-calculator-app.ondigitalocean.app"
static_sites:
- name: frontend
  source_dir: webapp
  github:
    repo: C0n0r92/calc2
    branch: main
    deploy_on_push: true
  environment_slug: node-js
  build_command: npm install && npm run build
  output_dir: dist
  envs:
  - key: NODE_ENV
    value: production
  - key: VITE_API_URL
    value: "https://mortgage-calculator-app-python-api.ondigitalocean.app"
  - key: VITE_GA_MEASUREMENT_ID
    value: "G-43FMLL1ZG0"
ingress:
  rules:
  - component:
      name: python-api
    match:
      path:
        prefix: /api
  - component:
      name: frontend
    match:
      path:
        prefix: /
domains:
- domain: mortgagepayoffcalculator.io
  type: PRIMARY
- domain: www.mortgagepayoffcalculator.io
  type: ALIAS