name: mortgage-calculator-app
services:
# React Frontend - Static Site
- name: frontend
  type: static_site
  source_dir: webapp
  github:
    repo: C0n0r92/calc2
    branch: main
  build_command: npm install && npm run build
  output_dir: dist
  envs:
  - key: NODE_ENV
    value: production
  - key: VITE_API_URL
    value: "/api"
  - key: VITE_GA_MEASUREMENT_ID
    value: "G-43FMLL1ZG0"
  routes:
  - path: /

# Python FastAPI Backend
- name: python-api
  type: service
  source_dir: python-backend
  github:
    repo: C0n0r92/calc2
    branch: main
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8000
  dockerfile_path: python-backend/Dockerfile
  health_check:
    http_path: /health
  envs:
  - key: ENVIRONMENT
    value: production
  - key: ALLOWED_ORIGINS
    value: "https://mortgagepayoffcalculator.io,https://www.mortgagepayoffcalculator.io"
  routes:
  - path: /api
    preserve_path_prefix: true

domains:
- domain: mortgagepayoffcalculator.io
  type: PRIMARY
- domain: www.mortgagepayoffcalculator.io
  type: ALIAS