name: mortgage-calculator-app
region: nyc

# React Frontend - Static Site
static_sites:
- name: frontend
  source_dir: frontend
  github:
    repo: C0n0r92/calc2
    branch: main
    deploy_on_push: true
  build_command: npm install && npm run build
  output_dir: dist
  environment_slug: node-js
  envs:
  - key: NODE_ENV
    value: production
  - key: VITE_API_URL
    value: "https://mortgage-calculator-app-backend.ondigitalocean.app"
  - key: VITE_GA_MEASUREMENT_ID
    value: "G-43FMLL1ZG0"

# Python Backend - Service
services:
- name: backend
  github:
    repo: C0n0r92/calc2
    branch: main
    deploy_on_push: true
  environment_slug: python
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-1gb
  http_port: 8000
  run_command: python main.py
  envs:
  - key: ENVIRONMENT
    value: production
  - key: ALLOWED_ORIGINS
    value: '["https://mortgage-calculator-app.ondigitalocean.app"]'

# Routing Configuration
ingress:
  rules:
  - component:
      name: backend
    match:
      path:
        prefix: /api
  - component:
      name: frontend
    match:
      path:
        prefix: /

# Custom Domain (Optional)
domains:
- domain: mortgagepayoffcalculator.io
  type: PRIMARY
- domain: www.mortgagepayoffcalculator.io
  type: ALIAS
