name: mortgage-calculator-app
services:
# React Frontend - With buildpack detection
- name: frontend
  source_dir: webapp
  github:
    repo: C0n0r92/mortgage_payoff_calculator
    branch: main
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  build_command: npm install --include=dev && npm run build
  run_command: npm run preview -- --host 0.0.0.0 --port 3000
  environment_slug: node-js
  envs:
  - key: NODE_ENV
    value: production
  - key: VITE_API_URL
    value: "/api"
  - key: VITE_GA_MEASUREMENT_ID
    value: "G-43FMLL1ZG0"
  routes:
  - path: /

# Rails Backend API - With buildpack detection
- name: rails-api
  source_dir: backend-api
  github:
    repo: C0n0r92/mortgage_payoff_calculator
    branch: main
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  build_command: bundle install && bundle exec rails db:prepare
  run_command: bundle exec rails server -b 0.0.0.0 -p 8080
  environment_slug: ruby
  envs:
  - key: RAILS_ENV
    value: production
  - key: RAILS_MASTER_KEY
    value: ae744e6df9969de7459815939e7f7ed3
  - key: DATABASE_URL
    value: ${managed-db.DATABASE_URL}
  - key: PORT
    value: "8080"
  routes:
  - path: /api
    preserve_path_prefix: true

databases:
- name: managed-db
  engine: PG
  production: true

domains:
- domain: mortgagepayoffcalculator.io
  type: PRIMARY
- domain: www.mortgagepayoffcalculator.io
  type: ALIAS