name: mortgage-calculator-app
region: lon
domains:
- domain: mortgagepayoffcalculator.io
  type: PRIMARY
- domain: www.mortgagepayoffcalculator.io
  type: ALIAS

services:
# Rails Backend API
- name: rails-api
  source_dir: /mortgage_calculator_api
  github:
    repo: C0n0r92/mortgage_payoff_calculator
    branch: main
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  build_command: bundle install
  run_command: bundle exec rails server -b 0.0.0.0 -p $PORT
  envs:
  - key: RAILS_ENV
    value: production
  - key: RAILS_LOG_TO_STDOUT
    value: "true"
  - key: PORT
    value: "3000"
  - key: SECRET_KEY_BASE
    value: "7cf6edda93cf09a4f69db15991af58789ee1264cd2ae54d49a9f52cedea88e291aa352a0d9d67e5feb1a63eb093ef9ff2c7f7e540867d1ab992e7a1d942e92d9"
  routes:
  - path: /api
    preserve_path_prefix: true

# React Frontend
- name: frontend
  source_dir: /
  github:
    repo: C0n0r92/mortgage_payoff_calculator
    branch: main
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 4173
  build_command: npm install && npm run build
  run_command: npm run preview -- --host 0.0.0.0 --port $PORT
  envs:
  - key: NODE_ENV
    value: production
  - key: VITE_API_URL
    value: "/api"
  - key: VITE_GA_MEASUREMENT_ID
    value: "G-43FMLL1ZG0"
  routes:
  - path: /

static_sites: []
